#!/bin/bash

# Install Git Large File Storage
sudo apt install -y git-lfs
git lfs install

#Install System-Level Dependencies
sudo apt install -y sox libsox-fmt-mp3 alsa-utils libcap-dev portaudio19-dev

#Create Virtual Environment and Install Req's
python -m venv venv
source ./venv/bin/activate
pip install -r ./requirements.txt

deactivate

# Install node and npm by way of nvm
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
# source ~/.bashrc
# nvm install node
# cd server && npm i && cd ..